### PR TITLE
task(issue-136): Add export button for Sales

### PR DESCRIPTION
**Pull request by xujulien99**
Created a button that exports info of the sales tab

Note: I also changed the javascript function's name 'exportLogs' to 'exportTasks' in master.blade.php since the function is not only used by logs. The export button for the Logs still works (I changed exportLogs to exportTasks  in log-page.blade as well). @pirasunt

### CODE REVIEW

**Review by pirasunt — APPROVED** [review]
Looks good, tested and it works.

**Review by pirasunt — CHANGES_REQUESTED** [review]
Support to export to PDF is required as well

**Review by mlee97 — APPROVED** [review]
Good job!

**Review by WanProduction — APPROVED** [review]
amazeballs

**Review by pirasunt — APPROVED** [review]

**Pull request merged**
