### PR TITLE
feat(issue-182-184): product manager and inventory person changes

### PR DESCRIPTION
**Pull request by DGovi**
-product manager is now a user
-product manager has access to the inventory page (so far)
-product manager is the only one that can add part, materials and bikes
-inventory guy can no longer add those
-created seed for product manager with name thankyou essam

-DELETED product_manager.blade.php file

### CODE REVIEW

**Review by pirasunt — CHANGES_REQUESTED** [review]
- Currently, the Product Manager has the ability to order materials. This should only be allowed by the Inventory person.

- Can you add a restriction for ordering materials? So that only the inventory person has access

**Comment by DGovi** [comment]
yessir

**Review by CeliaCaii — APPROVED** [review]
Tested and looks good, approved

**Review by mlee97 — APPROVED** [review]
Thank you Essam!

**Review by pirasunt — APPROVED** [review]

**Pull request merged**
